// GENERATED by frontend/design/compiler — do not edit. Source: frontend/design/tokens/ (D29). Regenerate: bun run generate:tokens
export const themes = ["paper", "linen", "graphite", "carbon"] as const;
export type Theme = (typeof themes)[number];
export const defaultTheme: Theme = "paper";
