// Code generated by cmd/generate; DO NOT EDIT.
// Source of truth: internal/domain (asset.go, volume.go), per C13/C15.
// Regenerate with `make generate` after changing the Go source.

export type FileType =
  | "audio"
  | "document"
  | "image"
  | "raw"
  | "vector"
  | "video";

export type ColorLabel =
  | "blue"
  | "green"
  | "orange"
  | "purple"
  | "red"
  | "yellow";

export type Flag =
  | "pick"
  | "reject";

export type FileStatus =
  | "missing"
  | "offline"
  | "online";

export type VolumeKind =
  | "external_drive"
  | "local"
  | "nfs"
  | "smb";

export type VolumeConnectivity =
  | "offline"
  | "online";

export type SyncMode =
  | "manual"
  | "scheduled"
  | "watched";

export type EnrichmentKind =
  | "clipping"
  | "phash"
  | "sharpness"
  | "thumbnail";

export type CollectionKind =
  | "manual"
  | "smart";

export type CreateFolderOutcomeKind =
  | "absorbed"
  | "already_tracked_within"
  | "created"
  | "needs_confirmation";