// Code generated by internal/seam/generate; DO NOT EDIT.
// Source of truth: internal/domain (asset.go, source.go), per C13.
// Regenerate with `make generate-seam` after changing the Go source.

export type FileType =
  | "audio"
  | "document"
  | "image"
  | "raw"
  | "vector"
  | "video";

export type ColorLabel =
  | "blue"
  | "green"
  | "orange"
  | "purple"
  | "red"
  | "yellow";

export type Flag =
  | "pick"
  | "reject";

export type FileStatus =
  | "missing"
  | "offline"
  | "online";

export type SourceKind =
  | "external_drive"
  | "local"
  | "nfs"
  | "smb";

export type SourceConnectivity =
  | "offline"
  | "online";