// Code generated by cmd/generate; DO NOT EDIT.
// Source of truth: internal/seam (apierror.go), per C13/C15.
// Regenerate with `make generate` after changing the Go source.

export type ApiErrorKind =
  | "degraded"
  | "domain"
  | "transport"
  | "unexpected";

export type ErrorCode =
  | "conflict"
  | "not_found"
  | "query_invalid"
  | "query_version_too_new"
  | "validation"
  | "volume_offline";