// Code generated by internal/seam/generate; DO NOT EDIT.
// Source of truth: internal/seam (apierror.go), per C13.
// Regenerate with `make generate-seam` after changing the Go source.

export type ApiErrorKind =
  | "degraded"
  | "domain"
  | "transport"
  | "unexpected";

export type ErrorCode =
  | "conflict"
  | "not_found"
  | "query_invalid"
  | "query_version_too_new"
  | "source_offline"
  | "validation";