// Code generated by cmd/generate; DO NOT EDIT.
// Source of truth: internal/seam (events.go), per C13/C15.
// Regenerate with `make generate` after changing the Go source.

export type EventTopic =
  | "catalog"
  | "jobs"
  | "sync"
  | "watcher";

export type EventType =
  | "changed"
  | "done"
  | "historyChanged"
  | "progress"
  | "volumeStatus";

export type JobState =
  | "cancelled"
  | "done"
  | "failed"
  | "running";