// Code generated by cmd/generate; DO NOT EDIT.
// Source of truth: internal/catalog + internal/seam (struct json tags), per C13/C15.
// Regenerate with `make generate` after changing the Go source.

import type { CollectionKind, ColorLabel, CreateFolderOutcomeKind, EnrichmentKind, FileStatus, FileType, Flag, SyncMode, VolumeConnectivity, VolumeKind } from "./enums";
import type { EventTopic, EventType, JobState } from "./events";

/** The slim grid-card projection. The seam adapter layers thumbURL + the kind discriminator on top. */
export interface AssetRow {
  id: string;
  volumeId: string;
  filename: string;
  fileType: FileType;
  fileStatus: FileStatus;
  rating: number | null;
  colorLabel: ColorLabel | null;
  flag: Flag | null;
  width: number | null;
  height: number | null;
  durationSecs: number | null;
  cameraModel: string | null;
  capturedAt: string | null;
  ingestedAt: string;
  thumbnailAt: string | null;
  relativePath: string;
  sizeBytes: number;
  enriching?: EnrichmentKind[];
  failed?: EnrichmentKind[];
}

/** The full-asset detail projection GetAsset returns — the inspector's read. */
export interface AssetDetail {
  id: string;
  volumeId: string;
  filename: string;
  extension: string;
  mimeType: string;
  fileType: FileType;
  fileStatus: FileStatus;
  relativePath: string;
  sizeBytes: number;
  mtime: string;
  ingestedAt: string;
  width: number | null;
  height: number | null;
  durationSecs: number | null;
  capturedAt: string | null;
  cameraMake: string | null;
  cameraModel: string | null;
  lensModel: string | null;
  focalLengthMm: number | null;
  aperture: number | null;
  shutterSpeed: string | null;
  iso: number | null;
  gpsLat: number | null;
  gpsLon: number | null;
  colorSpace: string | null;
  bitDepth: number | null;
  title: string | null;
  caption: string | null;
  creator: string | null;
  copyright: string | null;
  rating: number | null;
  colorLabel: ColorLabel | null;
  flag: Flag | null;
  note: string | null;
  extendedMetadata?: Record<string, unknown>;
}

/** The one C8 event envelope. */
export interface Envelope {
  topic: EventTopic;
  type: EventType;
  payload: unknown;
  timestamp: string;
}

/** catalog/changed payload. */
export interface CatalogChange {
  scope?: string;
  ids?: string[];
}

/** jobs/progress payload (C9). */
export interface JobProgress {
  jobId: string;
  kind: string;
  label: string;
  state: JobState;
  done: number;
  total: number;
  totalKnown: boolean;
  stage?: string;
  cancelable: boolean;
  message?: string;
  queueDepth?: Record<string, number>;
}

/** Completion tally carried by JobDone. */
export interface JobSummary {
  added: number;
  updated: number;
  skipped: number;
  errors: number;
}

/** jobs/done payload. */
export interface JobDone {
  jobId: string;
  kind: string;
  state: JobState;
  summary?: JobSummary;
  error?: string;
}

/** catalog/historyChanged payload. */
export interface HistoryState {
  canUndo: boolean;
  canRedo: boolean;
  undoLabel?: string;
  redoLabel?: string;
}

/** watcher/volumeStatus payload. */
export interface VolumeStatus {
  volumeId: string;
  status: string;
}

/** A storage volume with its tracked-root folders — a node in the getFolderTree forest (D41). */
export interface VolumeNode {
  id: string;
  name: string;
  kind: VolumeKind;
  connectivity: VolumeConnectivity;
  assetCount: number;
  folders: FolderNode[];
}

/** One node in a volume's folder tree; recursive via children (D41). */
export interface FolderNode {
  id: string;
  name: string;
  path: string;
  syncMode?: SyncMode;
  assetCount: number;
  children: FolderNode[];
}

/** A collection projected for the rail; flat list, parentId adjacency (D41). */
export interface CollectionNode {
  id: string;
  name: string;
  parentId?: string;
  kind: CollectionKind;
  assetCount: number | null;
}

/** One tracked root whose sync policy would change under a proposed absorb (D41). */
export interface FolderBehaviorChange {
  folderId: string;
  folderName: string;
  currentSyncMode: SyncMode;
  newSyncMode: SyncMode;
}

/** The disposition of a createFolder attempt plus the folders it touched (D41). */
export interface CreateFolderOutcome {
  kind: CreateFolderOutcomeKind;
  folderId?: string;
  absorbedFolderIds?: string[];
  behaviorChanges?: FolderBehaviorChange[];
}

/** The sparse updateFolder input (name / sync mode). */
export interface FolderPatch {
  name?: string;
  syncMode?: SyncMode;
}
