// Code generated by cmd/generate; DO NOT EDIT.
// Source of truth: internal/catalog + internal/seam (struct json tags), per C13/C15.
// Regenerate with `make generate` after changing the Go source.

import type { ColorLabel, FileStatus, FileType, Flag } from "./enums";
import type { EventTopic, EventType, JobState } from "./events";

/** The slim grid-card projection. The seam adapter layers thumbURL + the kind discriminator on top. */
export interface AssetRow {
  id: string;
  sourceId: string;
  filename: string;
  fileType: FileType;
  fileStatus: FileStatus;
  rating: number | null;
  colorLabel: ColorLabel | null;
  flag: Flag | null;
  width: number | null;
  height: number | null;
  durationSecs: number | null;
  cameraModel: string | null;
  capturedAt: string | null;
  ingestedAt: string;
  thumbnailAt: string | null;
  relativePath: string;
  sizeBytes: number;
}

/** The one C8 event envelope. */
export interface Envelope {
  topic: EventTopic;
  type: EventType;
  payload: unknown;
  timestamp: string;
}

/** catalog/changed payload. */
export interface CatalogChange {
  scope?: string;
  ids?: string[];
}

/** jobs/progress payload (C9). */
export interface JobProgress {
  jobId: string;
  kind: string;
  label: string;
  state: JobState;
  done: number;
  total: number;
  totalKnown: boolean;
  stage?: string;
  cancelable: boolean;
  message?: string;
}

/** Completion tally carried by JobDone. */
export interface JobSummary {
  added: number;
  updated: number;
  skipped: number;
  errors: number;
}

/** jobs/done payload. */
export interface JobDone {
  jobId: string;
  kind: string;
  state: JobState;
  summary?: JobSummary;
  error?: string;
}

/** catalog/historyChanged payload. */
export interface HistoryState {
  canUndo: boolean;
  canRedo: boolean;
  undoLabel?: string;
  redoLabel?: string;
}

/** watcher/sourceStatus payload. */
export interface SourceStatus {
  sourceId: string;
  status: string;
}
