// Code generated by cmd/generate; DO NOT EDIT.
// Source of truth: internal/ast (vocabulary.go, types.go), per C13/C15.
// Regenerate with `make generate` after changing the Go source.

export type TokenField =
  | "cameraMake"
  | "cameraModel"
  | "caption"
  | "capturedAt"
  | "colorLabel"
  | "copyright"
  | "creator"
  | "fileStatus"
  | "fileType"
  | "filename"
  | "flag"
  | "height"
  | "ingestedAt"
  | "lensModel"
  | "rating"
  | "source"
  | "tag"
  | "text"
  | "title"
  | "width";

export type TokenOperator =
  | "contains"
  | "empty"
  | "eq"
  | "gte"
  | "has"
  | "in"
  | "lacks"
  | "lte"
  | "matches"
  | "neq"
  | "notEmpty"
  | "notIn"
  | "notUnder"
  | "notWithin"
  | "startsWith"
  | "under"
  | "within";

export type ValueKind =
  | "dateRange"
  | "entityReference"
  | "enum"
  | "freeText"
  | "numeric"
  | "tagReference"
  | "text";

export type ScopeKind =
  | "collection"
  | "folder"
  | "library"
  | "tag";

export type GroupOp =
  | "and"
  | "not"
  | "or";

export type SortField =
  | "capturedAt"
  | "filename"
  | "ingestedAt"
  | "rating"
  | "size";

export type SortDir =
  | "asc"
  | "desc";

export interface FieldGrammar {
  operators: readonly TokenOperator[];
  kind: ValueKind;
  suggestable: boolean;
}

export const fieldGrammar = {
  cameraMake: { operators: ["eq", "neq", "contains", "startsWith", "empty", "notEmpty"], kind: "text", suggestable: true },
  cameraModel: { operators: ["eq", "neq", "contains", "startsWith", "empty", "notEmpty"], kind: "text", suggestable: true },
  caption: { operators: ["eq", "neq", "contains", "startsWith", "empty", "notEmpty"], kind: "text", suggestable: false },
  capturedAt: { operators: ["within", "notWithin", "empty", "notEmpty"], kind: "dateRange", suggestable: false },
  colorLabel: { operators: ["in", "notIn", "empty", "notEmpty"], kind: "enum", suggestable: false },
  copyright: { operators: ["eq", "neq", "contains", "startsWith", "empty", "notEmpty"], kind: "text", suggestable: true },
  creator: { operators: ["eq", "neq", "contains", "startsWith", "empty", "notEmpty"], kind: "text", suggestable: true },
  fileStatus: { operators: ["in", "notIn"], kind: "enum", suggestable: false },
  fileType: { operators: ["in", "notIn"], kind: "enum", suggestable: false },
  filename: { operators: ["eq", "neq", "contains", "startsWith"], kind: "text", suggestable: false },
  flag: { operators: ["in", "notIn", "empty", "notEmpty"], kind: "enum", suggestable: false },
  height: { operators: ["eq", "neq", "gte", "lte", "empty", "notEmpty"], kind: "numeric", suggestable: false },
  ingestedAt: { operators: ["within", "notWithin"], kind: "dateRange", suggestable: false },
  lensModel: { operators: ["eq", "neq", "contains", "startsWith", "empty", "notEmpty"], kind: "text", suggestable: true },
  rating: { operators: ["eq", "neq", "gte", "lte", "empty", "notEmpty"], kind: "numeric", suggestable: false },
  source: { operators: ["in", "notIn"], kind: "entityReference", suggestable: false },
  tag: { operators: ["has", "lacks", "under", "notUnder", "empty", "notEmpty"], kind: "tagReference", suggestable: false },
  text: { operators: ["matches"], kind: "freeText", suggestable: false },
  title: { operators: ["eq", "neq", "contains", "startsWith", "empty", "notEmpty"], kind: "text", suggestable: false },
  width: { operators: ["eq", "neq", "gte", "lte", "empty", "notEmpty"], kind: "numeric", suggestable: false },
} as const satisfies Record<TokenField, FieldGrammar>;
