// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ast} from '../models';
import {seam} from '../models';

export function AssetIDSlice(arg1:ast.Query,arg2:ast.Arrangement,arg3:number,arg4:number):Promise<Array<string>>;

export function DistinctValues(arg1:string):Promise<Array<string>>;

export function GetAsset(arg1:string):Promise<seam.AssetDetail>;

export function IndexOfAsset(arg1:ast.Query,arg2:ast.Arrangement,arg3:string):Promise<any>;

export function QueryAssets(arg1:ast.Query,arg2:ast.Arrangement,arg3:ast.Page):Promise<seam.QueryResult>;

export function RemoveFromCatalog(arg1:Array<string>):Promise<void>;

export function UpdateAssets(arg1:seam.UpdateTarget,arg2:seam.TriagePatchInput):Promise<void>;
