// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssetIDSlice(arg1, arg2, arg3, arg4) {
  return window['go']['seam']['AssetService']['AssetIDSlice'](arg1, arg2, arg3, arg4);
}

export function DistinctValues(arg1) {
  return window['go']['seam']['AssetService']['DistinctValues'](arg1);
}

export function GetAsset(arg1) {
  return window['go']['seam']['AssetService']['GetAsset'](arg1);
}

export function IndexOfAsset(arg1, arg2, arg3) {
  return window['go']['seam']['AssetService']['IndexOfAsset'](arg1, arg2, arg3);
}

export function QueryAssets(arg1, arg2, arg3) {
  return window['go']['seam']['AssetService']['QueryAssets'](arg1, arg2, arg3);
}

export function RemoveFromCatalog(arg1) {
  return window['go']['seam']['AssetService']['RemoveFromCatalog'](arg1);
}

export function UpdateAssets(arg1, arg2) {
  return window['go']['seam']['AssetService']['UpdateAssets'](arg1, arg2);
}
