// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {seam} from '../models';
import {domain} from '../models';

export function AddToCollection(arg1:string,arg2:Array<string>):Promise<void>;

export function CreateCollection(arg1:seam.CollectionInput):Promise<domain.Collection>;

export function DeleteCollection(arg1:string):Promise<void>;

export function ListCollections():Promise<Array<domain.Collection>>;

export function RemoveFromCollection(arg1:string,arg2:Array<string>):Promise<void>;

export function UpdateCollection(arg1:string,arg2:seam.CollectionPatch):Promise<void>;
