// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToCollection(arg1, arg2) {
  return window['go']['seam']['CollectionService']['AddToCollection'](arg1, arg2);
}

export function CreateCollection(arg1) {
  return window['go']['seam']['CollectionService']['CreateCollection'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['seam']['CollectionService']['DeleteCollection'](arg1);
}

export function ListCollections() {
  return window['go']['seam']['CollectionService']['ListCollections']();
}

export function RemoveFromCollection(arg1, arg2) {
  return window['go']['seam']['CollectionService']['RemoveFromCollection'](arg1, arg2);
}

export function UpdateCollection(arg1, arg2) {
  return window['go']['seam']['CollectionService']['UpdateCollection'](arg1, arg2);
}
