// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['seam']['ImportService']['CancelJob'](arg1);
}

export function StartImport(arg1) {
  return window['go']['seam']['ImportService']['StartImport'](arg1);
}
