// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1:string):Promise<void>;

export function StartImport(arg1:string):Promise<string>;
