// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function GetSettings():Promise<settings.Settings>;

export function ListKeybindings():Promise<settings.Keybindings>;

export function ResetKeybindings():Promise<void>;

export function SetKeybinding(arg1:string,arg2:string):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;
