// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['seam']['SettingsService']['GetSettings']();
}

export function ListKeybindings() {
  return window['go']['seam']['SettingsService']['ListKeybindings']();
}

export function ResetKeybindings() {
  return window['go']['seam']['SettingsService']['ResetKeybindings']();
}

export function SetKeybinding(arg1, arg2) {
  return window['go']['seam']['SettingsService']['SetKeybinding'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['seam']['SettingsService']['UpdateSettings'](arg1);
}
