// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {seam} from '../models';
import {domain} from '../models';

export function CreateSource(arg1:seam.SourceInput):Promise<domain.Source>;

export function ListSources():Promise<Array<domain.Source>>;

export function UpdateSource(arg1:string,arg2:seam.SourcePatch):Promise<void>;
