// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSource(arg1) {
  return window['go']['seam']['SourceService']['CreateSource'](arg1);
}

export function ListSources() {
  return window['go']['seam']['SourceService']['ListSources']();
}

export function UpdateSource(arg1, arg2) {
  return window['go']['seam']['SourceService']['UpdateSource'](arg1, arg2);
}
