// Emission (design-constitution §22, D29): resolved themes → tokens.css (CSS custom
// properties + type-role unit classes), tokens.ts (theme names for TS), and
// tokens-reference.json (the design library's table). Names are the strict path
// mirror: `--alx-` + token path with dots → hyphens — zero curation (ratified at
// task-23 pickup, 2026-07-17). type-scale.* composites are deliberately not
// emitted: the type ROLES supersede them in code (§9).

import type { ResolvedSource, ResolvedToken, ThemeTokens } from "./resolve";

const GENERATED_HEADER =
    "GENERATED by frontend/design/compiler — do not edit. Source: frontend/design/tokens/ (D29). Regenerate: bun run generate:tokens";

export interface EmittedFiles {
    css: string;
    typescript: string;
    referenceJson: string;
}

function variableName(path: string): string {
    return `--alx-${path.replaceAll(".", "-")}`;
}

interface Dimension {
    value: number;
    unit: string;
}

interface ShadowLayer {
    color: unknown;
    offsetX: Dimension;
    offsetY: Dimension;
    blur: Dimension;
    spread: Dimension;
}

function cssColor(value: unknown): string {
    const color = value as { components: [number, number, number]; alpha?: number };
    const [l, c, h] = color.components;
    const alpha = color.alpha !== undefined && color.alpha !== 1 ? ` / ${color.alpha}` : "";
    return `oklch(${l} ${c} ${h}${alpha})`;
}

function cssDimension(value: unknown): string {
    const dimension = value as Dimension;
    return `${dimension.value}${dimension.unit}`;
}

function cssFontFamily(value: unknown): string {
    return (value as string[]).map((family) => (/\s/.test(family) ? `"${family}"` : family)).join(", ");
}

function cssShadow(token: ResolvedToken): string {
    const layers = (Array.isArray(token.value) ? token.value : [token.value]) as ShadowLayer[];
    const inset = token.extensions?.alx?.inset === true ? "inset " : "";
    return layers
        .map(
            (layer) =>
                `${inset}${cssDimension(layer.offsetX)} ${cssDimension(layer.offsetY)} ${cssDimension(layer.blur)} ${cssDimension(layer.spread)} ${cssColor(layer.color)}`,
        )
        .join(", ");
}

function cssGradient(token: ResolvedToken, tokens: ThemeTokens): string {
    const stops = token.value as { color: unknown; position: number }[];
    const angleToken = tokens.get("fun.gradient-angle");
    const angle = typeof angleToken?.value === "number" ? angleToken.value : 0;
    const stopList = stops.map((stop) => `${cssColor(stop.color)} ${stop.position * 100}%`).join(", ");
    return `linear-gradient(${angle}deg, ${stopList})`;
}

/** CSS value for one non-typography token, or undefined for kinds emitted elsewhere. */
function cssValue(token: ResolvedToken, tokens: ThemeTokens): string | undefined {
    switch (token.type) {
        case "color":
            return cssColor(token.value);
        case "dimension":
        case "duration":
            return cssDimension(token.value);
        case "number":
            return String(token.value);
        case "fontWeight":
            return String(token.value);
        case "fontFamily":
            return cssFontFamily(token.value);
        case "cubicBezier": {
            const [x1, y1, x2, y2] = token.value as [number, number, number, number];
            return `cubic-bezier(${x1}, ${y1}, ${x2}, ${y2})`;
        }
        case "shadow":
            return cssShadow(token);
        case "gradient":
            return cssGradient(token, tokens);
        default:
            // typography deliberately lands here too: both call sites branch on it
            // before calling cssValue, so reaching it is a bug worth a loud throw.
            throw new Error(`no CSS form for token "${token.path}" of type "${token.type}"`);
    }
}

const OMITTED_PREFIXES = ["type-scale."];

function omitted(path: string): boolean {
    return OMITTED_PREFIXES.some((prefix) => path.startsWith(prefix));
}

interface TypographyValue {
    fontFamily: unknown;
    fontSize: Dimension;
    fontWeight: number;
    lineHeight: Dimension;
    letterSpacing: string;
}

/** Per-property variables for a typography composite (strict mirror + CSS property names). */
function typographyVariables(token: ResolvedToken): [string, string][] {
    const typography = token.value as TypographyValue;
    const base = variableName(token.path);
    return [
        [`${base}-font-family`, cssFontFamily(typography.fontFamily)],
        [`${base}-font-size`, cssDimension(typography.fontSize)],
        [`${base}-font-weight`, String(typography.fontWeight)],
        [`${base}-line-height`, cssDimension(typography.lineHeight)],
        [`${base}-letter-spacing`, typography.letterSpacing],
    ];
}

/** The role's unit class: all properties together + the paired ink (§9: type is a
 * unit). `:where()` zeroes the selector's specificity — the class supplies role
 * DEFAULTS, and any component declaration (a fill rung's inverse ink, a state
 * shift) must win regardless of stylesheet injection order. Found the hard way:
 * equal specificity made fill's label ink-on-ink invisible on carbon. */
function typeRoleClass(token: ResolvedToken): string {
    const roleName = token.path.split(".").at(-1);
    const base = variableName(token.path);
    const ink = token.extensions?.alx?.ink;
    const lines = [
        `:where(.alx-type-${roleName}) {`,
        `    font-family: var(${base}-font-family);`,
        `    font-size: var(${base}-font-size);`,
        `    font-weight: var(${base}-font-weight);`,
        `    line-height: var(${base}-line-height);`,
        `    letter-spacing: var(${base}-letter-spacing);`,
    ];
    if (ink !== undefined) lines.push(`    color: var(${variableName(ink)});`);
    if (token.extensions?.alx?.numerals === "tabular") lines.push(`    font-variant-numeric: tabular-nums;`);
    lines.push("}");
    return lines.join("\n");
}

function sortedTokens(tokens: ThemeTokens): ResolvedToken[] {
    return [...tokens.values()].sort((first, second) => first.path.localeCompare(second.path));
}

/** Roles that are hue bindings carry their bound hue's paired steps through the
 * alias for free: `--alx-accent-on` (on-solid ink — text on an accent fill) and
 * `--alx-accent-ring` (the world-varying ring step, 2026-07-17). Deliberately just
 * these two roles — labels are swatch-only and unused pairings are noise. */
const HUE_BINDING_CARRIERS = ["accent", "attention"];
const CARRIED_STEPS: { suffix: string; step: string }[] = [
    { suffix: "-on", step: "on-solid" },
    { suffix: "-ring", step: "ring" },
];

function variableBlock(tokens: ThemeTokens, only: (token: ResolvedToken) => boolean): string[] {
    const lines: string[] = [];
    for (const token of sortedTokens(tokens)) {
        if (omitted(token.path) || !only(token)) continue;
        if (token.type === "typography") {
            for (const [name, value] of typographyVariables(token)) lines.push(`    ${name}: ${value};`);
            continue;
        }
        const value = cssValue(token, tokens);
        if (value !== undefined) lines.push(`    ${variableName(token.path)}: ${value};`);
    }
    // Carried steps ride the SIBLING token's varying flag, not the binding's — the
    // binding is invariant while its ring step differs per world.
    for (const carrier of HUE_BINDING_CARRIERS) {
        const binding = tokens.get(carrier);
        if (binding?.aliasOf === undefined) continue;
        for (const { suffix, step } of CARRIED_STEPS) {
            const sibling = tokens.get(binding.aliasOf.replace(/\.solid$/, `.${step}`));
            if (sibling === undefined || !only(sibling)) continue;
            lines.push(`    ${variableName(carrier)}${suffix}: ${cssValue(sibling, tokens)};`);
        }
    }
    return lines.sort();
}

export function emit(source: ResolvedSource, accentEligible: string[]): EmittedFiles {
    const defaultTokens = source.themes.get(source.defaultTheme);
    if (defaultTokens === undefined) throw new Error(`default theme "${source.defaultTheme}" missing`);

    // tokens.css — :root carries the complete default theme; other themes override
    // only their varying subset (index.html stamps data-theme before first paint).
    const cssParts: string[] = [`/* ${GENERATED_HEADER} */`];
    cssParts.push(`:root {\n${variableBlock(defaultTokens, () => true).join("\n")}\n}`);
    for (const themeName of source.themeNames) {
        if (themeName === source.defaultTheme) continue;
        const tokens = source.themes.get(themeName);
        if (tokens === undefined) throw new Error(`theme "${themeName}" missing`);
        cssParts.push(`[data-theme="${themeName}"] {\n${variableBlock(tokens, (token) => token.varying).join("\n")}\n}`);
    }
    const roleClasses = sortedTokens(defaultTokens)
        .filter((token) => token.type === "typography" && !omitted(token.path))
        .map(typeRoleClass);
    cssParts.push(...roleClasses);
    const css = cssParts.join("\n\n") + "\n";

    // tokens.ts — the theme vocabulary, derived from the resolver's contexts (C15:
    // one source; lib/theme.ts imports these instead of declaring its own list).
    const typescript = [
        `// ${GENERATED_HEADER}`,
        `export const themes = [${source.themeNames.map((name) => `"${name}"`).join(", ")}] as const;`,
        `export type Theme = (typeof themes)[number];`,
        `export const defaultTheme: Theme = "${source.defaultTheme}";`,
        ``,
    ].join("\n");

    // tokens-reference.json — the design library's table: every emitted token with
    // its CSS form, per theme where varying.
    const reference = {
        $generated: GENERATED_HEADER,
        themes: source.themeNames,
        defaultTheme: source.defaultTheme,
        accentEligible,
        tokens: sortedTokens(defaultTokens)
            .filter((token) => !omitted(token.path))
            .map((token) => {
                const shape = {
                    path: token.path,
                    type: token.type,
                    varying: token.varying,
                    role: token.extensions?.alx?.role,
                    pin: token.extensions?.alx?.pin,
                };
                if (token.type === "typography") {
                    return { ...shape, variables: Object.fromEntries(typographyVariables(token)) };
                }
                if (!token.varying) {
                    return { ...shape, css: cssValue(token, defaultTokens) };
                }
                const perTheme: Record<string, string | undefined> = {};
                for (const themeName of source.themeNames) {
                    const tokens = source.themes.get(themeName);
                    const themeToken = tokens?.get(token.path);
                    if (tokens === undefined || themeToken === undefined) continue;
                    perTheme[themeName] = cssValue(themeToken, tokens);
                }
                return { ...shape, css: perTheme };
            }),
    };
    const referenceJson = JSON.stringify(reference, null, 2) + "\n";

    return { css, typescript, referenceJson };
}
