package main

// docs/data-dictionary.md — the human-readable projection of the same
// vocabularies the TS emitters consume. Generated so it cannot lie; a schema
// change shows up as a readable dictionary diff in review. The conceptual
// companion (taxonomy, representation rules, the "why") is the hand-written
// docs/vocabulary.md — that file explains, this one enumerates.

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/akmadian/alexandria/internal/ast"
)

func renderDataDictionary() []byte {
	var buffer bytes.Buffer

	buffer.WriteString("# Alexandria Data Dictionary\n\n")
	buffer.WriteString("<!-- Code generated by cmd/generate; DO NOT EDIT. -->\n")
	buffer.WriteString("<!-- Regenerate with `make generate` after changing internal/domain, internal/ast, or internal/seam. -->\n\n")
	buffer.WriteString("Generated inventory of every shared vocabulary: the nouns, their enums, the\n")
	buffer.WriteString("query grammar, the events, and the shared wire models. Concepts and\n")
	buffer.WriteString("representation rules live in [vocabulary.md](vocabulary.md); this file is the\n")
	buffer.WriteString("mechanical truth, regenerated from the Go declarations.\n\n")

	writeCrosswalkMap(&buffer)
	writeFieldTable(&buffer)
	writeQueryShapes(&buffer)
	writeEnumSection(&buffer)
	writeEventSection(&buffer)
	writeModelSection(&buffer)

	return buffer.Bytes()
}

func writeCrosswalkMap(buffer *bytes.Buffer) {
	buffer.WriteString("## The crosswalk map\n\n")
	buffer.WriteString("How the canonical declarations project into every medium, and what enforces\n")
	buffer.WriteString("each edge (generation = compile error on drift; tests = red CI; crosswalk =\n")
	buffer.WriteString("hand-maintained against an external standard, reflection-tested).\n\n")
	buffer.WriteString("```mermaid\n")
	buffer.WriteString("flowchart LR\n")
	buffer.WriteString("    domain[\"internal/domain<br/>Asset + enums (nouns)\"]\n")
	buffer.WriteString("    ast[\"internal/ast<br/>token grammar (adjectives)\"]\n")
	buffer.WriteString("    seam[\"internal/seam<br/>verbs, events, errors\"]\n")
	buffer.WriteString("    sqlite[(\"sqlite catalog<br/>assets table\")]\n")
	buffer.WriteString("    ts[\"frontend _generated-types<br/>vocabulary/enums/errors/events/models\"]\n")
	buffer.WriteString("    xmp[\"XMP sidecars<br/>(Rating, Label, dc:subject, ...)\"]\n")
	buffer.WriteString("    extract[\"metadata.Metadata<br/>(EXIF/IPTC extraction)\"]\n")
	buffer.WriteString("    dict[\"docs/data-dictionary.md\"]\n")
	buffer.WriteString("    domain -->|referenced types| ast\n")
	buffer.WriteString("    domain -->|generated: type-check discovery| ts\n")
	buffer.WriteString("    ast -->|compiled: kind strategies + derived columns| sqlite\n")
	buffer.WriteString("    ast -->|generated: unions + fieldGrammar| ts\n")
	buffer.WriteString("    seam -->|generated: catalogs + models| ts\n")
	buffer.WriteString("    domain <-->|crosswalk: exiftool property map| xmp\n")
	buffer.WriteString("    extract -->|reflection-tested subset| domain\n")
	buffer.WriteString("    domain -->|generated| dict\n")
	buffer.WriteString("    ast -->|generated| dict\n")
	buffer.WriteString("    seam -->|generated| dict\n")
	buffer.WriteString("```\n\n")
}

func writeFieldTable(buffer *bytes.Buffer) {
	buffer.WriteString("## Filterable fields (the token grammar)\n\n")
	buffer.WriteString("One row per `ast.Field`. Operators derive from kind + nullability; columns\n")
	buffer.WriteString("derive from the field name (virtual fields compile through joins instead).\n\n")
	buffer.WriteString("| Field | Kind | Nullable | Column | Operators | Suggestable |\n")
	buffer.WriteString("|---|---|---|---|---|---|\n")

	fields := ast.AllFields()
	sort.Slice(fields, func(i, j int) bool { return fields[i] < fields[j] })
	columns := ast.FieldColumns()

	for _, field := range fields {
		spec, _ := ast.LookupField(field)
		column := columns[field]
		if column == "" {
			column = "— (virtual)"
		}
		operators := make([]string, 0, len(spec.Operators()))
		for _, operator := range spec.Operators() {
			operators = append(operators, string(operator))
		}
		fmt.Fprintf(buffer, "| `%s` | %s | %v | `%s` | %s | %v |\n",
			field, spec.Kind, spec.Nullable, column, strings.Join(operators, ", "), spec.Suggestable)
	}
	buffer.WriteString("\n")
}

func writeQueryShapes(buffer *bytes.Buffer) {
	buffer.WriteString("## Query shapes\n\n")
	members := loadEnumMembers(astPackage, queryShapeTypes)
	for _, typeName := range queryShapeTypes {
		fmt.Fprintf(buffer, "- **%s**: %s\n", typeName, joinSorted(members[typeName]))
	}
	buffer.WriteString("\n")
}

func writeEnumSection(buffer *bytes.Buffer) {
	buffer.WriteString("## Domain enums\n\n")
	members := loadEnumMembers(domainPackage, domainEnumTypes)
	for _, typeName := range domainEnumTypes {
		fmt.Fprintf(buffer, "- **%s**: %s\n", typeName, joinSorted(members[typeName]))
	}
	buffer.WriteString("\n")
}

func writeEventSection(buffer *bytes.Buffer) {
	buffer.WriteString("## Events (C8) and errors\n\n")
	eventMembers := loadEnumMembers(seamPackage, []string{"Topic", "EventType", "JobState"})
	fmt.Fprintf(buffer, "- **Topics**: %s\n", joinSorted(eventMembers["Topic"]))
	fmt.Fprintf(buffer, "- **Event types**: %s\n", joinSorted(eventMembers["EventType"]))
	fmt.Fprintf(buffer, "- **Job states**: %s\n", joinSorted(eventMembers["JobState"]))
	codeMembers := loadEnumMembers(seamPackage, seamCodeTypes)
	fmt.Fprintf(buffer, "- **ApiError kinds**: %s\n", joinSorted(codeMembers["ApiErrorKind"]))
	fmt.Fprintf(buffer, "- **Error codes**: %s\n", joinSorted(codeMembers["ErrorCode"]))
	buffer.WriteString("\n")
}

func writeModelSection(buffer *bytes.Buffer) {
	buffer.WriteString("## Shared wire models (models.ts)\n\n")
	buffer.WriteString("Reflected from Go structs whose json tags are the wire contract.\n\n")
	for _, entry := range modelManifest {
		shortPkg := entry.pkg[strings.LastIndex(entry.pkg, "/")+1:]
		fmt.Fprintf(buffer, "- **%s** (`internal/%s`) — %s\n", entry.typeName, shortPkg, entry.doc)
	}
}

func joinSorted(members []string) string {
	sorted := append([]string{}, members...)
	sort.Strings(sorted)
	quoted := make([]string, len(sorted))
	for i, member := range sorted {
		quoted[i] = "`" + member + "`"
	}
	return strings.Join(quoted, ", ")
}
