package main

import (
	"bytes"
	"strings"
	"testing"
)

// TestDeterministic is the acceptance guard (seam impl/14 §5): two runs over the
// same Go sources must be byte-identical, since map iteration order is
// nondeterministic and the output is committed + freshness-gated.
func TestDeterministic(t *testing.T) {
	for _, render := range []struct {
		name string
		fn   func() []byte
	}{
		{"vocabulary", renderVocabulary},
		{"domain enums", renderDomainEnums},
		{"seam codes", renderSeamCodes},
		{"seam events", renderSeamEvents},
		{"models", renderModels},
		{"data dictionary", renderDataDictionary},
	} {
		if !bytes.Equal(render.fn(), render.fn()) {
			t.Errorf("%s: render is not deterministic", render.name)
		}
	}
}

// TestVocabularyShape checks the pieces the frontend depends on are present: the
// DO-NOT-EDIT header, all three unions, and the satisfies-gated grammar table.
func TestVocabularyShape(t *testing.T) {
	source := string(renderVocabulary())

	wants := []string{
		"// Code generated by cmd/generate; DO NOT EDIT.",
		"export type TokenField =",
		"export type TokenOperator =",
		"export type ValueKind =",
		// The query-shape unions (C15 — retired hand-written TS copies).
		"export type ScopeKind =",
		"export type GroupOp =",
		"export type SortField =",
		"export type SortDir =",
		`  | "library"`,    // ScopeKind member (the frontend/09 alphabet)
		`  | "capturedAt"`, // SortField member (TokenField spellings)
		"} as const satisfies Record<TokenField, FieldGrammar>;",
		// A representative field with its grammar, proving LookupField wiring.
		`rating: { operators: ["eq", "neq", "gte", "lte", "empty", "notEmpty"], kind: "numeric", suggestable: false },`,
	}
	for _, want := range wants {
		if !strings.Contains(source, want) {
			t.Errorf("vocabulary.ts missing %q", want)
		}
	}
}

// TestDomainEnumsShape checks every domain enum is emitted as a literal union
// (not a TS enum — frontend/09 forbids that), with sorted string values.
func TestDomainEnumsShape(t *testing.T) {
	source := string(renderDomainEnums())

	wants := []string{
		"export type FileType =",
		"export type ColorLabel =",
		"export type Flag =",
		"export type FileStatus =",
		"export type VolumeKind =",
		"export type VolumeConnectivity =",
		`  | "external_drive"`, // VolumeKind member, proving raw values (not TS names) are emitted
	}
	for _, want := range wants {
		if !strings.Contains(source, want) {
			t.Errorf("enums.ts missing %q", want)
		}
	}
	if strings.Contains(source, "enum ") {
		t.Error("enums.ts emitted a TS `enum` keyword; frontend/09 mandates literal unions")
	}
}

// TestSeamCodesShape checks the error catalog is emitted as literal unions the
// frontend switches on, with representative kind + code members present.
func TestSeamCodesShape(t *testing.T) {
	source := string(renderSeamCodes())

	wants := []string{
		"export type ApiErrorKind =",
		"export type ErrorCode =",
		`  | "unexpected"`,            // an ApiErrorKind member
		`  | "query_version_too_new"`, // an ErrorCode member
	}
	for _, want := range wants {
		if !strings.Contains(source, want) {
			t.Errorf("errors.ts missing %q", want)
		}
	}
	if strings.Contains(source, "enum ") {
		t.Error("errors.ts emitted a TS `enum` keyword; frontend/09 mandates literal unions")
	}
}

// TestSeamEventsShape checks the C8 catalog is emitted as literal unions the event
// pump switches on: the topic, type, and job-state sets, with Topic renamed to the
// less-generic EventTopic in the TS namespace.
func TestSeamEventsShape(t *testing.T) {
	source := string(renderSeamEvents())

	wants := []string{
		"export type EventTopic =",
		"export type EventType =",
		"export type JobState =",
		`  | "catalog"`,      // an EventTopic member
		`  | "volumeStatus"`, // an EventType member
		`  | "cancelled"`,    // a JobState member
	}
	for _, want := range wants {
		if !strings.Contains(source, want) {
			t.Errorf("events.ts missing %q", want)
		}
	}
	if strings.Contains(source, "enum ") {
		t.Error("events.ts emitted a TS `enum` keyword; frontend/09 mandates literal unions")
	}
}

// TestUnionMembersSorted guards the determinism precondition: union members are
// emitted in sorted order.
func TestUnionMembersSorted(t *testing.T) {
	for _, source := range []string{string(renderVocabulary()), string(renderDomainEnums()), string(renderSeamCodes()), string(renderSeamEvents())} {
		for _, block := range strings.Split(source, "export type ")[1:] {
			var previous string
			for _, line := range strings.Split(block, "\n") {
				line = strings.TrimSpace(line)
				if !strings.HasPrefix(line, `| "`) {
					continue
				}
				member := strings.Trim(strings.TrimPrefix(line, "| "), `";`)
				if previous != "" && member < previous {
					t.Errorf("union members not sorted: %q came after %q", member, previous)
				}
				previous = member
			}
		}
	}
}
