name: CI

on:
  push:
    branches: [main, dev]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - "Makefile"
      - "internal/Makefile"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - "Makefile"
      - "internal/Makefile"
      - ".github/workflows/ci.yml"

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6
          install-only: true
      - run: make check-backend
